# -*- mode: ruby -*-
# vi: set ft=ruby :

# VARIABLES (SUBSTITUEIX 'ab' PER LES TEVES INICIALS)
BOX_IMAGE = "debian/bookworm64"
PROVIDER = "virtualbox"
NOM_MAQUINA_VIRTUAL = "pj9f4a7.1_ab"
NUM_CPUS = 2
MEMORIA_RAM = 2048
HOSTNAME = "pj9f4a7.1-ab.fjeclot.net"
CARPETA_MAQ_FIS = "../codis" # Des de 'vm' la carpeta 'codis' és a la carpeta superior (../)
CARPETA_MAQ_VIR = "/home/vagrant/codis"
PORT_VIR1 = 80
PORT_FIS1 = 8000
PORT_VIR2 = 443
PORT_FIS2 = 8443
PROT = "tcp"

# CONFIGURACIÓ DE LA MÀQUINA
Vagrant.configure("2") do |config|
  # BOX
  config.vm.box = BOX_IMAGE

  # CONFIGURACIÓ ESPECÍFICA DEL PROVIDER
  config.vm.provider PROVIDER do |provider|
    provider.name = NOM_MAQUINA_VIRTUAL
    provider.memory = MEMORIA_RAM
    provider.cpus = NUM_CPUS
    provider.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end

  # CONFIGURACIÓ GENERAL
  config.vm.hostname = HOSTNAME
  config.vm.synced_folder CARPETA_MAQ_FIS,CARPETA_MAQ_VIR
  # Port 1: Redirecció del port HTTP (80 a la VM -> 8000 a la Física)
  config.vm.network "forwarded_port", guest: PORT_VIR1, host: PORT_FIS1, protocol: PROT
  # Port 2: Redirecció del port HTTPS (443 a la VM -> 8443 a la Física)
  config.vm.network "forwarded_port", guest: PORT_VIR2, host: PORT_FIS2, protocol: PROT

  # PROGRAMARI A INSTAL·LAR I ORDRES A EXECUTAR DURANT LA CREACIÓ DE LA MÀQUINA
  config.vm.provision "shell", inline: <<-SHELL
#
# 1- Actualització de la llista de programari. Instal·lació del programari general
#
sudo apt update -y
sudo apt install -y aptitude net-tools whois

#
# 2- Ordres d'instal·lació de Docker. Permís a l'usuari vagrant per utilitzar Docker sense sudo
#
# 2.1- Programari necessari per poder instal·lar Docker
sudo apt install -y apt-transport-https ca-certificates curl gnupg

# 2.2- Clau GPG per comprovar la signatura i integritat del programari descarregat
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg

# 2.3- Afegint el dipòsit a sources.list
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# 2.4- Descarregant el programari bàsic de Docker
sudo apt update -y
sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# 2.5- Afegint l'usuari vagrant al grup docker
# Nota: La comanda 'gpasswd' ja no és l'estàndard a Debian/Ubuntu. S'utilitza 'usermod'.
sudo usermod -aG docker vagrant

SHELL
end
